### ISSUE TITLE
remark v15

### ISSUE THREAD

**Issue by kachkaev** [Eyas/md-heading-id#9]
👋  @Eyas!

Remark v15 [was released in Sep 2023](https://github.com/remarkjs/remark/releases/tag/15.0.0) and its popularity is [getting close](https://www.npmjs.com/package/remark?activeTab=versions) to v14:

![Screenshot 2024-05-27 at 04 13 15](https://github.com/Eyas/md-heading-id/assets/608862/1cbceb6e-e938-4a4d-92f5-120febc9a1f2)

`remark-custom-heading-id` anticipates `remark` v14, which blocks the migration to v15:

https://github.com/Eyas/md-heading-id/blob/4fbabc25ac993f20ffa9554a41bfed15a29b133d/packages/remark-custom-heading-id/package.json#L39-L41

What are you thoughts on upgrading?

**Comment by kachkaev** [comment]
There might be an issue upstream: https://github.com/mdx-js/mdx/issues/2485

**Comment by Eyas** [comment]
Fixed and release 2.0.0
